# Generated by Django 3.2.3 on 2021-05-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_filed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('progress', 'In Progress'), ('done', 'Done'), ('invalid', 'Invalid')], default='new', max_length=8),
        ),
    ]
