# Generated by Django 3.2.3 on 2021-05-25 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0003_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='completed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='filed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Filed', to=settings.AUTH_USER_MODEL),
        ),
    ]
